### ISSUE TITLE
[Feature Request] Mob spawn circle/square from x location

### ISSUE THREAD

**Issue by BourbonCrow** [Ceddini/CoreKeeperMapTool#22]
able to make your own circle/square (not sure what game use i assume circle) on map that shows the 208 distance from player where mob can spawn. circle doesnt have to be from where player is can be moved by 2 slides x and y

this is to help making mob farms

**Comment by BourbonCrow** [comment]
basically just make the custom circle you already can make moveable from 0,0

**Comment by Ceddini** [comment]
Anything different from #9?
