### ISSUE TITLE
Copper ore color value typo

### ISSUE THREAD

**Issue by Orfeu** [Ceddini/CoreKeeperMapTool#3]
https://github.com/Ceddini/CoreKeeperMapTool/blob/0485d85f437d954ccaa139187207297853d2df1c/src/data/tilecolormap.js#L62
https://github.com/Ceddini/CoreKeeperMapTool/blob/0485d85f437d954ccaa139187207297853d2df1c/src/data/tilecolormap.js#L75

Isn't the red value 237?

**Comment by Ceddini** [comment]
Yes it is! I already fixed it yesterday on the release, but forgot to push changes to the repo. Thanks for the info! :)
