### ISSUE TITLE
Copper Boulder Highlighting Issue

### ISSUE THREAD

**Issue by ekabina** [Ceddini/CoreKeeperMapTool#4]
Good Morning,
I'm not a coder so I don't know what the solution is but the copper boulders do not appear to be highlighting when selecting them in the settings menu. All other boulders highlight. I turn the tile transparency down to 2% when using the boulder highlighting to try and find the boulders I'm looking for and all are functioning except Copper. 

Using Opera GX for a browser if that's helpful in troubleshooting at all.

**Comment by Ceddini** [comment]
That is weird. It should've already been fixed since the 13th.
I've accidentally switched around two numbers, so the color codes were wrong, but I fixed it in
7d12158bae11b2ce1198c95f436af3af8866b67f

**Comment by Ceddini** [comment]
I've reconfigured the server to force updates of the page every day, so that should hopefully solve the issue.

**Comment by Ceddini** [comment]
I'm going to assume that it's no longer an issue. If the issue persists or a new one crops up, feel free to reopen / make a new issue.

**Comment by 6lancmange** [comment]
Interesting that I found this, because I seem to have the exact opposite problem! I remember I found some non-copper boulders, but the map tool only highlights the copper ones.
![obraz](https://user-images.githubusercontent.com/26997029/203998382-a1b934e0-e1a0-406d-bbac-9d105e66d7dd.png)
